name: 'Publish to npm'
description: 'Action to publish package to npm'

inputs:
  npm-username:
    description: 'NPM username'
    required: true
  npm-password:
    description: 'NPM password'
    required: true
  npm-email:
    description: 'NPM email'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Publish to npm
      shell: bash
      run: |
        # npm Login
        echo -e "${{ inputs.npm-username }}\n${{ inputs.npm-password }}\n${{ inputs.npm-email }}" | npm login
        # Publish the package
        npm publish --access public
