name: 'Publish to npm'
description: 'Publish the package to npm'

inputs:
  npm-token:
    description: 'NPM token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Verify npm user
      shell: bash
      run: npm whoami
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Publish to npm
      shell: bash
      run: |
        # Authenticate with npm
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc
        # Publish the package
        npm publish
