name: 'Publish to npm'
description: 'Action to publish package to npm'

inputs:
  npm-username:
    description: 'NPM username'
    required: true
  npm-password:
    description: 'NPM password'
    required: true
  npm-email:
    description: 'NPM email'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Install npm-cli-login
      shell: bash
      run: npm install -g npm-cli-login

    - name: Publish to npm
      shell: bash
      run: |
        # Authenticate with NPM using npm-cli-login
        echo -e "${{ inputs.npm-username }}\n${{ inputs.npm-password }}\n${{ inputs.npm-email }}" | npm adduser
        echo -e "${{ inputs.npm-username }}\n${{ inputs.npm-password }}\n${{ inputs.npm-email }}" | npm login
        npm-cli-login -u "${{ inputs.npm-username }}" -p "${{ inputs.npm-password }}" -e "${{ inputs.npm-email }}"
        # Publish the package
        npm publish --access public
