name: Continuous Integration

on:
  push:
    branches: 
      - main
      - development
      - feature/*
  pull_request:
    branches: 
      - main
      - development

jobs:
  build:
    name: Continuous Integration and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Node.js CI Action
        uses: ./.github/actions/ci
        with:
          node-version: '20'
      
      - name: Publish artifact to npm
        uses: ./.github/actions/publish
        with:
          npm-username: ${{ secrets.NPM_USERNAME }}
          npm-password: ${{ secrets.NPM_PASSWORD }}
          npm-email: ${{ secrets.NPM_EMAIL }}
