name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Node.js CI Action
        uses: ./.github/actions/action.yml
        with:
          node-version: '14'
